GET  http://localhost:3000/api/v1/getdefault/2


###
POST http://localhost:3000/api/v1/getcustom
Content-Type: application/json

{
    "text": "着急"
}

###
POST http://localhost:3000/api/v1/getpinyin
Content-Type: application/json

{
    "text": "号"
}