GET  http://localhost:8080/api/v1/getdefault/2


###
POST http://localhost:8080/api/v1/getcustom
Content-Type: application/json

{
    "text": "不复还"
}

###
POST http://localhost:8080/api/v1/getpinyin
Content-Type: application/json

{
    "text": "重"
}